#!/bin/bash
# This is a config file for Linux Live Kit build script.
# You shouldn't need to change anything expect LIVEKITNAME

# Live Kit Name. Defaults to 'linux';
LIVEKITNAME="sbc"

# Kernel file, will be copied to your Live Kit
# Your kernel must support aufs and squashfs. Debian Jessie's kernel is ready
# out of the box.
VMLINUZ=/vmlinuz

# Kernel version. Change it to "3.2.28" for example, if you are building
# Live Kit with a different kernel than the one you are actually running
KERNEL=$(uname -r)

# If you require network support in initrd, for example to boot over
# PXE or to load data using 'from' boot parameter from a http server,
# you will need network modules included in your initrd.
# This is disabled by default since most people won't need it.
# To enable, set to true
NETWORK=true

# Temporary directory to store livekit filesystem
LIVEKITDATA=/tmp/$LIVEKITNAME-data-$$

# Bundle extension, for example 'sb' for .sb extension
BEXT=sb

# Directory with kernel .ko modules, can be different in some distros
LMK="lib/modules/$KERNEL"

#Root password 
ROOTPASSWORD="plusnet"

#Ubuntu 18
UBUNTU=false

#RTPENGINE VERSION
RTPENGINE="mr7.1.1.1"

#KAMAILIO VERSION
KAMAILIO="5.2.1"

#SIP AND RTP ENGINE. In the future can be openSIP and rtpproxy if needed
SIP_ENGINE="kamailio"
RTP_ENGINE="rtpengine"

#Clean up repository always.
REPOSITORY_CACHE=false
#

