#!/bin/ash

case $1 in
  "start")
    echo 1 > /proc/sys/vm/overcommit_memory
    ulimit -n 100000
    echo "Start test";
    ;;
  "stop")
    echo "Stop";
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    return
    ;;
esac
