#!/bin/sh

if [ -e /usr/sbin/iptables-legacy ]; then
        IPTABLES=/usr/sbin/iptables-legacy
else
        IPTABLES=/sbin/iptables
fi

if [ -e /usr/sbin/iptables-legacy-restore ]; then
        IPTABLES_RESTORE=/usr/sbin/iptables-legacy-restore
else
        IPTABLES_RESTORE=/sbin/iptables-restore
fi

apply_firewall () {

        echo "Apply firewall"        
	$IPTABLES_RESTORE < /etc/firewall.conf	

        return 0;
}

flush_firewall() {

	echo "Flushing firewall"
	$IPTABLES -F
	return 0;
}



case "$1" in
start)
	apply_firewall
        ;;

stop)

	flush_firewall
        ;;
reload)

	flush_firewall;
	apply_firewall;
        ;;

*)
        echo "Usage: /etc/init.d/firewall {start|stop|reload}"
        exit 1
        ;;
esac


exit 0
