#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
# Must be a valid filename
NAME=rtpengine-daemon
PIDFILE=/var/run/$NAME.pid
DESC="RTP/media proxy"
DEFAULTS=/etc/default/${NAME}
DAEMON=/usr/bin/rtpengine
CONFIG=/etc/rtpengine/rtpengine.conf
DAEMON_OPTS=""
TABLE=1

test -f $DAEMON || exit 0

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

[ -z "$PIDFILE" ] && PIDFILE="/var/run/rtpengine.pid"

set -e

OPTIONS="--config-file ${CONFIG}"

OPTIONS="$OPTIONS --table=$TABLE"

if test "$FORK" = "no" ; then
	OPTIONS="$OPTIONS --foreground"
fi

if test "$LOG_STDERR" = "yes" ; then
	OPTIONS="$OPTIONS --log-stderr"
fi

if [ -e /usr/sbin/iptables-legacy ]; then
	IPTABLES=/usr/sbin/iptables-legacy
else
	IPTABLES=/sbin/iptables
fi

if [ -e /usr/sbin/ip6tables-legacy ]; then
	IP6TABLES=/usr/sbin/ip6tables-legacy
else
	IP6TABLES=/sbin/ip6tables
fi

case "$1" in
  start)
	set +e
	echo -n "Starting $DESC: $NAME"
	set +e
	modprobe xt_RTPENGINE
	if [ -e /proc/rtpengine/control ]; then
		echo "del $TABLE" > /proc/rtpengine/control 2>/dev/null
	fi

	if [ "$CREATE_IPTABLES_CHAIN" != "no" ]; then
		$IPTABLES -N rtpengine 2> /dev/null
		$IPTABLES -D INPUT -j rtpengine 2> /dev/null
		$IPTABLES -I INPUT -j rtpengine
		$IP6TABLES -N rtpengine 2> /dev/null
		$IP6TABLES -D INPUT -j rtpengine 2> /dev/null
		$IP6TABLES -I INPUT -j rtpengine
	fi
	if $IPTABLES -C INPUT -j rtpengine 1> /dev/null 2> /dev/null && $IPTABLES -n --list rtpengine 1> /dev/null 2> /dev/null; then
		$IPTABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
		$IPTABLES -I rtpengine -p udp -j RTPENGINE --id "$TABLE"
		$IP6TABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
		$IP6TABLES -I rtpengine -p udp -j RTPENGINE --id "$TABLE"
	else
		echo ""
		echo "Missing rtpengine iptables chain - not starting"
		exit 0
	fi
	set -e

	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $OPTIONS || echo -n " already running"
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME

	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON
	if [ "$?" -ne 0 ]; then
		return $?
	fi
	set +e
	if [ -e /proc/rtpengine/control ]; then
		echo "del $TABLE" > /proc/rtpengine/control 2>/dev/null
	fi
	$IPTABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
	$IP6TABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
	rmmod xt_RTPENGINE 2>/dev/null
	set -e

	rm -f $PIDFILE
        echo "."
	;;
  restart)
	echo -n "Restarting $DESC: $NAME"
	start-stop-daemon --oknodo --stop --quiet --pidfile \
		$PIDFILE --exec $DAEMON
	if [ "$?" -ne 0 ]; then
		return $?
	fi
	rm -f $PIDFILE
	sleep 1
	set +e
	if [ -e /proc/rtpengine/control ]; then
		echo "del $TABLE" > /proc/rtpengine/control 2>/dev/null
	fi
	rmmod xt_RTPENGINE 2>/dev/null
	modprobe xt_RTPENGINE
	if [ "$CREATE_IPTABLES_CHAIN" != "no" ]; then
		$IPTABLES -D INPUT -j rtpengine 2> /dev/null
		$IP6TABLES -D INPUT -j rtpengine 2> /dev/null
		$IPTABLES -N rtpengine 2> /dev/null
		$IPTABLES -I INPUT -j rtpengine
		$IP6TABLES -N rtpengine 2> /dev/null
		$IP6TABLES -I INPUT -j rtpengine
	fi
	if $IPTABLES -C INPUT -j rtpengine 1> /dev/null 2> /dev/null && $IPTABLES -n --list rtpengine 1> /dev/null 2> /dev/null; then
		$IP6TABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
		$IPTABLES -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
		$IPTABLES -I rtpengine -p udp -j RTPENGINE --id "$TABLE"
		$IP6TABLES -I rtpengine -p udp -j RTPENGINE --id "$TABLE"
	else
		echo ""
                        echo "Missing rtpengine iptables chain - not starting"
                        exit 0
	fi
	set -e
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		$PIDFILE --exec $DAEMON  -- $OPTIONS
	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0
