#!/bin/ash

# Quick start-stop-daemon example, derived from Debian /etc/init.d/mount
set -e
umask 022
#
NAME=misc-system
INT=`cat /etc/dhcpinterface`

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting: "$NAME
	# add hostname to localhost - needed for testing env.
	echo "127.0.0.1 $(cat /etc/hostname)" >> /etc/hosts
	# start loopback device
	ip link set lo up
	ip -4 addr add 127.0.0.1/8 dev lo
	#make link
	TZ='CET'; export TZ	
	#echo -n "Starting DHCP..."
	#/sbin/dhclient $INT
        echo "."
	;;
  stop)
        echo -n "Stopping: "$NAME
        echo "."
	;;
  restart)
        echo -n "Restarting: "$NAME
        stop
        start
	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0
