#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/telegraf
set -e

umask 022

# Must be a valid filename
NAME=telegraf
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/usr/bin/$NAME
DAEMON_OPTS=" --config /etc/telegraf/telegraf.conf --pidfile $PIDFILE --quiet"
OPEN_FILE_LIMIT=65536

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        ulimit -n $OPEN_FILE_LIMIT
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS >> /dev/null 2>>/dev/null &
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS   >> /dev/null 2>>/dev/null &
        echo "."
        ;;

  *)
        echo "Usage: "$1" {start|stop|restart}"
        exit 1
esac

exit 0
